version: "2.2"

networks:
  network-devops:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.77.0/24

volumes:
  data-devops:

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    networks:
      network-devops:
        ipv4_address: 192.168.77.10
    volumes:
      - data-devops:/var/lib/postgresql/data:rw
    expose:
      - 5432
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate-db:
    container_name: migrate-db
    depends_on:
      db:
        condition: service_healthy
    image: image-devops
    build: .
    restart: "no"
    networks:
      network-devops:
        ipv4_address: 192.168.77.11
    links:
      - db
    command: python3 manage.py migrate

  run-server:
    container_name: run-server
    depends_on:
      db:
        condition: service_healthy
    image: image-devops
    restart: always
    networks:
      network-devops:
        ipv4_address: 192.168.77.12
    links:
      - db
    ports:
      - 8000:8000
    command: uwsgi --http :8000 --wsgi-file ./parrotsite/wsgi.py
